{% set name = "python-parakeet" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get("GIT_DESCRIBE_TAG") }}

source:
  git_url: ../
  path: ../

build:
  number: 0
  entry_points:
    - parakeet=parakeet.command_line:main
    - parakeet.export=parakeet.command_line:export
    - parakeet.run=parakeet.command_line:run
    - parakeet.pdb.get=parakeet.command_line.pdb:get
    - parakeet.pdb.read=parakeet.command_line.pdb:read
    - parakeet.config.show=parakeet.command_line.config:show
    - parakeet.config.new=parakeet.command_line.config:new
    - parakeet.config.edit=parakeet.command_line.config:edit
    - parakeet.sample.new=parakeet.command_line.sample:new
    - parakeet.sample.add_molecules=parakeet.command_line.sample:add_molecules
    - parakeet.sample.mill=parakeet.command_line.sample:mill
    - parakeet.sample.sputter=parakeet.command_line.sample:sputter
    - parakeet.sample.show=parakeet.command_line.sample:show
    - parakeet.simulate.potential=parakeet.command_line.simulate:potential
    - parakeet.simulate.exit_wave=parakeet.command_line.simulate:exit_wave
    - parakeet.simulate.optics=parakeet.command_line.simulate:optics
    - parakeet.simulate.image=parakeet.command_line.simulate:image
    - parakeet.simulate.simple=parakeet.command_line.simulate:simple
    - parakeet.simulate.ctf=parakeet.command_line.simulate:ctf
    - parakeet.analyse.reconstruct=parakeet.command_line.analyse:reconstruct
    - parakeet.analyse.average_particles=parakeet.command_line.analyse:average_particles
    - parakeet.analyse.average_all_particles=parakeet.command_line.analyse:average_all_particles
    - parakeet.analyse.extract=parakeet.command_line.analyse:extract
    - parakeet.analyse.refine=parakeet.command_line.analyse:refine
    - parakeet.analyse.correct=parakeet.command_line.analyse:correct
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cmake
    - fftw
    - cudatoolkit
    - distributed
    - gemmi
    - guanaco
    - h5py
    - maptools
    - mrcfile
    - numpy
    - pandas
    - pillow
    - pip
    - profet
    - pydantic==1.10.10
    - python
    - python-multem
    - pyyaml
    - scipy
    - starfile
    - importlib_resources
  run:
    - cmake
    - fftw
    - cudatoolkit
    - distributed
    - gemmi
    - guanaco
    - h5py
    - maptools
    - mrcfile
    - numpy
    - pandas
    - pillow
    - profet
    - pydantic==1.10.10
    - python
    - python-multem
    - pyyaml
    - scipy
    - starfile
    - importlib_resources

test:
  imports:
    - parakeet
    - parakeet.command_line
    - parakeet.command_line.analyse
    - parakeet.command_line.config
    - parakeet.command_line.sample
    - parakeet.command_line.simulate
    - parakeet.data
    - parakeet.freeze
  commands:
    - parakeet --help
    - parakeet.run --help
    - parakeet.export --help
    - parakeet.pdb.get --help
    - parakeet.pdb.read --help
    - parakeet.config.show --help
    - parakeet.config.new --help
    - parakeet.config.edit --help
    - parakeet.sample.new --help
    - parakeet.sample.add_molecules --help
    - parakeet.sample.mill --help
    - parakeet.sample.sputter --help
    - parakeet.sample.show --help
    - parakeet.simulate.potential --help
    - parakeet.simulate.exit_wave --help
    - parakeet.simulate.optics --help
    - parakeet.simulate.image --help
    - parakeet.simulate.simple --help
    - parakeet.simulate.ctf --help
    - parakeet.analyse.reconstruct --help
    - parakeet.analyse.average_particles --help
    - parakeet.analyse.average_all_particles --help
    - parakeet.analyse.extract --help
    - parakeet.analyse.refine --help
    - parakeet.analyse.correct --help
  requires:
    - mock
    - pytest
    - pytest-cov

about:
  home: The package home page
  summary: "A phantom generator"
