name: parakeet
base: core20

adopt-info: parakeet
summary: A digital twin for cryo-ET
description: |
  Parakeet is a digital twin for cryo electron tomography and stands for
  Program for Analysis and Reconstruction of Artificial data for Kryo ElEctron
  Tomography
license: GPL-3.0

contact: james.parkhurst@diamond.ac.uk
issues: https://github.com/rosalindfranklininstitute/parakeet/issues
source-code: https://github.com/rosalindfranklininstitute/parakeet
website: https://github.com/rosalindfranklininstitute/parakeet
icon: docs/source/images/parakeet_small.png

grade: devel
confinement: classic

architectures:
  - build-on: [amd64]

package-repositories:
  - type: apt
    formats: [deb]
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    key-server: hkp://keyserver.ubuntu.com:80
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64

build-packages:
  - g++
  - git
  - libfftw3-dev
  - wget
  - cuda-11-6

parts:
  parakeet:
    source: .
    source-type: git
    plugin: python
    build-environment:
      - CUDACXX: /usr/local/cuda/bin/nvcc
    stage-packages:
      - libfftw3-double3
      - libfftw3-single3
      - python3-venv
      - cuda-cudart-11-6
      - libcufft-11-6
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --always)"

apps:
  parakeet:
    command: bin/parakeet
    environment:
      PATH: $SNAP/bin
