microscope:
  beam:
    electrons_per_angstrom: 30
    energy: 300
    source_spread: 0.1
  detector:
    nx: 1000
    ny: 1000
    pixel_size: 1
  lens:
    c_10: -20000
    c_30: 2.7
    c_c: 2.7
sample:
  box:
  - 1000
  - 1000
  - 1000
  centre:
  - 500
  - 500
  - 500
  molecules: null
  shape:
    cube:
      length: 1000.0
    cuboid:
      length_x: 1000.0
      length_y: 1000.0
      length_z: 1000.0
    cylinder:
      length: 1000.0
      radius: 500.0
    margin:
    - 0
    - 0
    - 0
    type: cube
scan:
  mode: still
  num_images: 1
  start_angle: 0
  step_angle: 0
simulation:
  ice: false
