name: Sphinx documentation

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: deployment

    steps:
    
    - name: Install cuda
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda

    - name: Install fftw
      run: sudo apt-get install libfftw3-dev    

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black mypy types-PyYAML pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        export CUDACXX=/usr/local/cuda-11/bin/nvcc        
        python -m pip install -e .

    - name: Install documentation dependencies
      run: |
        pip install .[build_sphinx]
    
    - name: Build documentation
      run: |
        python setup.py build_sphinx
        cp -rv build/sphinx/html/* docs/
    
    - name: Publish to Github pages
      env:
        USER_EMAIL: "t1000@skynet.ai"
        USER_NAME: "github-actions"
      run: |
        git checkout -b gh-pages-temp
        git config user.name ${USER_NAME}
        git config user.email ${USER_EMAIL}
        git add -A
        git commit -m "Deploy documentation"
        git push -f origin HEAD:gh-pages
